os: linux
sudo: required
dist: trusty
language: generic
cache: 
  - apt
branches: 
  only: 
    - master
    - dev
env:
  global:
    - HOME=/home/travis
before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove -y postgresql*
  - sudo apt-get upgrade -qq --allow-unauthenticated
install:
  - sudo apt-get install -y binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev autoconf cmake pkg-config python
  - wget --timeout 60 https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
  - tar xzf master.tar.gz && mkdir -p kcov-master/build && cd kcov-master/build
  - cmake ..
  - make
  - sudo make install
  - cd ../../ && rm -rf kcov-master
before_script:
  - export PATH=/usr/bin:$PATH
  - rsync -av ./ ~/
  - mkdir -p ~/coverage
  - cd ~/ && ls
script:
  - kcov coverage opencv_install.sh || ./opencv_install.sh
  - kcov coverage opencv_test.sh || ./opencv_test.sh
after_success:
  - cd ~/ && bash <(curl -s https://codecov.io/bash) || { pwd; find ~/coverage; }
